DROP TABLE IF EXISTS information;

CREATE TABLE information (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  content TEXT UNIQUE NOT NULL,
  vendor BLOB NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);